CURRENT_DATASET: "CIENCIA_DA_COMPUTACAO"

DATASETS:
  CIENCIA_DA_COMPUTACAO:
    PERIOD_RANGE: 2017_2025_1
    RAW_DEACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/raw/inativos/raw_ciencia_da_computacao_inativos_2017_2025_1.csv
    RAW_ACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/raw/ativos/raw_ciencia_da_computacao_ativos_2017_2025_1.csv
    RAW_HISTORY_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/raw/historico/raw_ciencia_da_computacao_historico_escolar_2017_2025_1.csv
    PREPROCESSED_ACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/ativos/preprocessed_ciencia_da_computacao_ativos_2017_2025_1.csv
    PREPROCESSED_DEACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/inativos/preprocessed_ciencia_da_computacao_inativos_2017_2025_1.csv
    PREPROCESSED_HISTORY_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/historico/preprocessed_ciencia_da_computacao_historico_escolar_2017_2025_1.csv

REQUIRED_COLUMNS_DF_ACTIVE_AND_DF_DEACTIVE:
  - "Data Nascimento"
  - "Sexo"
  - "Raça"
  - "Estrangeiro"
  - "Nacionalidade"
  - "Naturalidade"
  - "UF Naturalidade"
  - "Estado Civil"
  - "Período"
  - "Situação atual"
  - "Data ocorrência"
  - "Estrutura"
  - "Período ingresso"
  - "Tipo ingresso"
  - "IMI"
  - "Coeficiente"
  - "Tipo de demanda"
  - "RGA_Anon"

REQUIRED_COLUMNS_DF_HISTORY:
  - "CH"
  - "Crédito"
  - "Nota"
  - "Faltas"
  - "Situação"
  - "Codigo_Turma"
  - "Nome_Disciplina"
  - "Codigo_Disciplina"
  - "Curso_Ofertante"
  - "Observacao"
  - "Equivalencia"
  - "Ano"
  - "Semestre"
  - "Frequencia"
  - "Falta_Excessiva"
  - "Percentual_Faltas"
  - "AnoSem"
  - "Idade_Academica"
  - "Qtd_Disciplinas_Semestre"
  - "Total_CH_Semestre"
  - "MG_Semestre"
  - "RGA_Anon"
