name: Build and Register Preprocessing Traning Task

on:
  push:
    branches:
      - dev-prod

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  IMAGE_NAME: preprocessing
  TASK_DEFINITION_FAMILY: preprocessing
  DOCKERFILE_PATH: infra/Dockerfile

jobs:
  register-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$IMAGE_NAME

          docker build \
            -f $DOCKERFILE_PATH \
            -t $IMAGE_URI:$IMAGE_TAG \
            -t $IMAGE_URI:latest \
            .

          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest

          echo "IMAGE_URI=$IMAGE_URI:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION_FAMILY \
            --query taskDefinition \
            > task-definition.json

      - name: Clean task definition
        run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-definition.json > clean-task-definition.json

      - name: Render new task definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: clean-task-definition.json
          container-name: preprocessing
          image: ${{ env.IMAGE_URI }}

      - name: Register new task definition revision
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://${{ steps.render-task-definition.outputs.task-definition }}
